<?php

namespace app\api\controller;

use think\Controller;
use think\Db;
use think\Request;

class Base extends Controller
{
    public $token;
    public $member;
    public $uid;
    public $post;

    public function _initialize()
    {
        //parent::_initialize(); // TODO: Change the autogenerated stub
        error_reporting(E_ERROR | E_PARSE );//关闭tp5严格模式
        header("Access-Control-Allow-Origin: *");//允许跨域
        $list = file_get_contents('php://input');
        $this->post = json_decode($list, true);
        //$this->token = input('token');
        if (!isset( $this->post['token']) || empty( $this->post['token'])){
            exit(Publics::ApiJson('', '', '201', '缺少参数token'));
        }
        $this->token = $this->post['token'];
        $member = Db::table('eacoo_member')->where('token', $this->token)->find();

        if (!$member) {
           exit(Publics::ApiJson('', $this->token, '201', 'token验证失败')) ;
        } else {
            $this->member = $member;
            $this->uid = $member['id'];
        }
    }

}
